# Conclusion
This report analyzes COVID-19 trends in the United States, comparing vaccine coverage and policy implementation, and provides some insights into the COVID-19 process and mitigation approaches.\
First, some key data on COVID-19 in the U.S. were obtained, which included data on cases and deaths by state, with weekly time frequency, as well as vaccine and policy data. The vaccine data include state and date dimensions, including vaccine distribution, series vaccine complete proportion, and additional dose proportion. policy data include state, policy release date, policy name, and The policy data include state, policy release date, policy name, and policy content. For ease of analysis, the report selects some of the variables in the above dataset.\
The report analyzes the target problem through visualization. First, a time series plot of cases and deaths is presented, which includes both the number of additions and the total number. The time series graphs show that there is an explosive trend in COVID-19 in both early 2021 and early 2022, and the trend is huge in early 2022. Next, a map of the United States is used to show the distribution and vaccination of the vaccine. The images show that the northeastern and northwestern United States have the highest vaccine coverage rates. This may be related to economic development, but could not be verified in this stuy. Next, Califonia was chosen as an example to compare the impact of vaccine versus additional dose coverage and policy implementation on COVID-19, respectively. The images illustrate that increasing the proportion of vaccination and improving vaccine distribution can effectively reduce the infection rate and the number of new deaths. However, in the face of policy relaxation, even ADDITIONAL DOSE could not reverse the trend of massive COVID-19 outbreaks. In other words, policy factors are still the main determinants of outbreak development.\
There are still many areas of improvement in this paper. For example, COVID-19 may reflect some information from an economic and political perspective. Are those states with high vaccination rates also more economically developed? Or do states with stricter outbreak control measures imply a different political direction, such as more Democratic or Republican-held states? Of course, all of this requires more data, and these data need to be collected through multiple sources.\
In the end, this report provides valid information for policy making and epidemic control. For example, the government should implement a strong containment policy at the beginning of the outbreak and accelerate resource investment and vaccine development. As vaccination rates increase, the policy should be gradually relaxed, but not too quickly. Finally, full relaxation of controls should be considered when virus virulence declines and when vaccines are fully available.\



