# Interactive component
This section will show the trend of the total cases of different states over time. The interactive function is used here, which is implemented by combining D3 with Bookdown. 

<script src="https://d3js.org/d3.v4.js"></script>

<!-- Initialize a select button -->
<select id="selectButton"></select>

<!-- Create a div where the graph will take place -->
<div id="my_dataviz"></div>

<!-- Color Scale -->
<script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>


<script>

// set the dimensions and margins of the graph
var margin = {top: 10, right: 30, bottom: 30, left: 60},
    width = 460 - margin.left - margin.right,
    height = 400 - margin.top - margin.bottom;

// append the svg object to the body of the page
var svg = d3.select("#my_dataviz")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")");

//Read the data
d3.csv("https://raw.githubusercontent.com/yuehanhu/footballplayervalue/main/pt1.csv", function(data) {
    // List of groups (here I have one group per column)
    var allGroup = d3.map(data, function(d){return(d.state)}).keys()
    // add the options to the button
    d3.select("#selectButton")
      .selectAll('myOptions')
     	.data(allGroup)
      .enter()
    	.append('option')
      .text(function (d) { return d; }) // text showed in the menu
      .attr("value", function (d) { return d; }) // corresponding value returned by the button
    // A color scale: one color for each group
    var myColor = d3.scaleOrdinal()
      .domain(allGroup)
      .range(d3.schemeSet2);
    var x = d3.scaleLinear()
      .domain([0,700])
      .range([ 0, width ]);
    svg.append("g")
      .attr("transform", "translate(0," + height + ")")
      .call(d3.axisBottom(x));
     // Add Y axis
    var y = d3.scaleLinear()
      .domain([0, d3.max(data, function(d) { return +d.Dist_Per_100K; })])
      .range([ height, 0 ]);
  svg.append("g")
      .call(d3.axisLeft(y));
    // Initialize line with first group of the list
    var line = svg
      .append('g')
      .append("path")
        .datum(data.filter(function(d){return d.state==allGroup[0]}))
        .attr("d", d3.line()
          .x(function(d) { return x(+d.Date) })
          .y(function(d) { return y(+d.Dist_Per_100K) })
        )
        .attr("stroke", function(d){ return myColor("valueA") })
        .style("stroke-width", 4)
        .style("fill", "none")
    function update(selectedGroup) {
      var dataFilter = data.filter(function(d){return d.state==selectedGroup})
      line
          .datum(dataFilter)
          .transition()
          .duration(10)
          .attr("d", d3.line()
            .x(function(d) { return x(+d.Date) })
            .y(function(d) { return y(+d.Dist_Per_100K) })
          )
          .attr("stroke", function(d){ return myColor(selectedGroup) })
    }
    d3.select("#selectButton").on("change", function(d) {
        var selectedOption = d3.select(this).property("value")
        update(selectedOption)
    })
})
</script>


 A button to switch between states is provided in the upper left corner of the figure above The horizontal coordinate of the graph is the number of days until the initial day of data, and the vertical coordinate is the total number of people. By switching states, it is possible to display multi-dimensional data.\



