# Proposal

## Research topic
This report will focus on the development of the outbreak, the implementation of outbreak prevention and control policies in each U.S. state, and the effectiveness of outbreak prevention and control policies. In the course of the analysis, different graphs will be put together for comparison, providing evidence of the effectiveness of vaccines and other epidemic prevention policies. The hope of this paper is to find those tools that can significantly improve the spread of COVID-19. This may be of slightly less use for viruses whose current virulence has diminished, but it does have significant implications for policy implementation and for future public health events that may be encountered.

## Data availability
Data for the report will be obtained from Centers for Disease Control and Prevention (CDC) at the URL https://covid.cdc.gov/covid-data-tracker/#datatracker-home. The dataset selected for the report is from the CDC's COVID Data Tracker. Several data files were considered for the analysis and visualization of the report. The first is Case, Death, & Laboratory Testing Trends by Location, a data file that monitors the rise and fall of COVID-19 cases, deaths, testing volume and percent positivity, nationally and by state. The temporal frequency of the data is weekly. The report will also show Case & Death Trends by Demographics, a data file that counts trends in case and death data by gender, race, and other disaggregated methods. In this dataset, interaction methods will be appropriately applied to demonstrate category characteristics. Next is Vaccination Distribution & Coverage. this dataset contains the distribution of Vaccinations with weekly frequency. This dataset is able to provide variation in the number of vaccines by state. When the number of Vaccinations increases, it somewhat reflects the importance of COVID-19 to the state government. Finally, the report uses Social Impact & Prevention, a dataExplore the social impacts of COVID-19 and see how human movement and COVID-19 prevention measures correspond to trends in the pandemic. It was released by the state government at the time the policy was issued. In the report, this will be shown in the same graph as the number of cases and deaths, reacting to the impact of the policy on the prevention and control of the epidemic. Also, interactive methods will be used to differentiate the performance of different states.\
In general, the report focuses on the following elements by presenting chronological charts, comparative charts with the inclusion of interactive features. First is the change in the number of cases, deaths and tests, and graphs of these data will provide detailed characteristics of the various stages of the outbreak. Next, the distribution of vaccines by state and vaccine coverage is shown on a map of the entire U.S. This provides a snapshot of how different states are approaching the outbreak. Another key piece of data is prophylaxis, which compares state outbreaks with prophylaxis data to show whether vaccination policies are having the desired effect. Also, the interactive approach will show the different measures and policy strengths of different states in the face of an outbreak.